feat(motd): create MOTD based on day
timberline-secondary/hs-puppet-environments pull request #2
Opened 2022-10-03 17:25 UTC by punctuations

Additions:
- cowsay
- custom cow for cowsay
- added cowsay to dependencies
- updated MOTD list

Dependencies:
- cowsay@latest

2022-10-04 01:06 UTC, tylerecouture requested changes

2022-10-04 01:06 UTC, tylerecouture commented on site/profile/files/config/h10-motd.sh
> +MOTDS=("Tetris is the GOAT." "Petition for morbius role!" "Hello, my name is Matthew Baker, I am currently trapped inside this computer, please send help I don't think Mr. C is sane." "Enjoy your tim
Can you put this in a text file instead, with each on its own line, then read that file?

2022-10-04 01:06 UTC, tylerecouture commented on site/profile/manifests/base.pp
> +
You'll also need to add the puppet code to install the custom cow file. See the code below for how the motd.sh is "saved" to each of the clients. Maybe save it in /etc/motd/

And the motd text list too I request above

2022-10-18 18:22 UTC, punctuations commented on site/profile/files/config/h10-motd.sh
> +MOTDS=("Tetris is the GOAT." "Petition for morbius role!" "Hello, my name is Matthew Baker, I am currently trapped inside this computer, please send help I don't think Mr. C is sane." "Enjoy your tim
fixed as per [dec3a29](https://github.com/timberline-secondary/hackerspace-control-repo/pull/2/commits/dec3a2992c8383f32609f24f8aaf7230e905d521)

2022-10-18 18:22 UTC, punctuations commented on site/profile/manifests/base.pp
> +
fixed as per [93dfac7](https://github.com/timberline-secondary/hackerspace-control-repo/pull/2/commits/93dfac7c92e88cc42c5b003aca0eb6b7ebf0d24b)

2022-11-01 21:48 UTC, merged